name: "Terraform Static Analysis"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: "Lint & Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Check Format
        run: terraform fmt -check

      - name: Initialize
        run: terraform init -backend=false

      - name: Validate Configuration
        run: terraform validate